# Generated by Django 4.2.10 on 2024-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra-Large'), ('XXL', 'XXL'), ('Xs', 'Xtra-small')], max_length=3, null=True),
        ),
    ]
