# Generated by Django 4.2.3 on 2024-01-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size2',
        ),
    ]
