# Generated by Django 4.2.3 on 2023-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=2, unique=True)),
            ],
        ),
    ]
