# Generated by Django 4.2.3 on 2023-12-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
